# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c5cc32626ad07f4ff946b781925b783bc811b57a620ff918bfda0504ccc3b0210596bcfadaf10cc89a8e82eeca775271dbf3cb51761e2ebdfe28d4c5274bfdd

test:
  secret_key_base: fe3794a468f459becc1927f38af6095a52dbfbdbc21e5ac649d1411b192adc726c74e12baf28944ca19d9208facacd7cee51e9f11196f2cbe791126244b0f15a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
